name: Deploy to CentOS

on:
  push:
    branches:
      - master   # deploy only when pushing to master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy App
        run: |
          /var/www/cash-flow-system/deploy.sh
