name: Test Runner

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from my CentOS self-hosted runner!"
